<a href="https://colab.research.google.com/github/lokesh31333/Python/blob/master/y.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy

In [ ]:
excel_file = 'y.xlsx'
tocode = pd.read_excel(excel_file)
# opening Excel File
tocode

   SaaS_ID  Availability  Reliability  Cost($)  Response Time(ms)
0      SP1       0.99988      0.99950    0.322                0.6
1      SP2       0.99968      0.99953    0.762                0.2
2      SP3       0.99935      0.99962    0.168                0.3
3      SP4       0.99988      0.99964    0.804                0.3
4      SP5       0.99959      0.99954    0.252                0.4
5      SP6       0.99963      0.99958    0.444                0.6
6      SP7       0.99939      0.99971    0.664                0.7
7      SP8       0.99918      0.99975    0.506                0.2
8      SP9       0.99995      0.99990    0.616                0.7
9     SP10       0.99958      0.99956    0.484                0.3
10    SP11       0.99945      0.99971    0.456                0.7
11    SP12       0.99981      0.99976    0.134                0.7
12    SP13       0.99911      0.99987    0.300                0.3
13    SP14       0.99924      0.99983    0.234                0.5
14    SP15       0.99912      0.99980    0.496                0.5
15    SP16       0.99948      0.99973    0.454                0.3
16    SP17       0.99952      0.99967    0.638                0.5
17    SP18       0.99999      0.99962    0.478                0.2
18    SP19       0.99944      0.99975    0.674                0.3
19    SP20       0.99943      0.99972    0.414                0.5
20    SP21       0.99987      0.99957    0.392                0.5
21    SP22       0.99959      0.99977    0.544                0.2
22    SP23       0.99970      0.99952    0.408                0.4
23    SP24       0.99999      0.99992    0.508                0.5

In [ ]:
Average_Availability_SaaS_ID = tocode["Availability"].mean(axis=0)

#Average_Availability_SaaS_ID


# calculating Average of Availability of SaaSID

In [ ]:
tocode['SP(Availability)Sensitivity ^^2'] = tocode['Availability']**2


#calculating SP(Availability)Sensitivity ^^2

In [ ]:
tocode['SLA * SP(Availability)Sensitivity ^^2'] = tocode['SP(Availability)Sensitivity ^^2']*0.99

#calculating SLA * SP(Availability)Sensitivity ^^2

In [ ]:
tocode['SLA* SP(Availability)Sensitivity ^^2 / Average Availability of SaaS_ID'] = tocode['SLA * SP(Availability)Sensitivity ^^2']/Average_Availability_SaaS_ID

#calculating SLA* SP(Availability)Sensitivity ^^2 / Average Availability of SaaS_ID

In [ ]:
tocode['Percentage of Availability'] = numpy.floor(((tocode['SLA* SP(Availability)Sensitivity ^^2 / Average Availability of SaaS_ID']/0.99)*100))

#calculating Percentage for Availability table

In [ ]:
availability_table = tocode[["SaaS_ID","Availability","SP(Availability)Sensitivity ^^2","SLA * SP(Availability)Sensitivity ^^2","SLA* SP(Availability)Sensitivity ^^2 / Average Availability of SaaS_ID","Percentage of Availability"]]
availability_table

#Total Availability Table Calculated and printed

   SaaS_ID  ...  Percentage of Availability
0      SP1  ...                       100.0
1      SP2  ...                        99.0
2      SP3  ...                        99.0
3      SP4  ...                       100.0
4      SP5  ...                        99.0
5      SP6  ...                        99.0
6      SP7  ...                        99.0
7      SP8  ...                        99.0
8      SP9  ...                       100.0
9     SP10  ...                        99.0
10    SP11  ...                        99.0
11    SP12  ...                       100.0
12    SP13  ...                        99.0
13    SP14  ...                        99.0
14    SP15  ...                        99.0
15    SP16  ...                        99.0
16    SP17  ...                        99.0
17    SP18  ...                       100.0
18    SP19  ...                        99.0
19    SP20  ...                        99.0
20    SP21  ...                       100.0
21    SP22  ...                        99.0
22    SP23  ...                        99.0
23    SP24  ...                       100.0

[24 rows x 6 columns]

In [ ]:
tocode['SP(Response Time)  Sensitivity ^^2'] = tocode['Response Time(ms)']**2


#calculating SP(Response Time)  Sensitivity ^^2

In [ ]:
Average_Response_Time_of_SaaS_ID = tocode["Response Time(ms)"].mean(axis=0)


#calculating Average_Response_Time_of_SaaS_ID

In [ ]:
tocode['SLA* SP(Response Time)  Sensitivity ^^2'] = tocode['SP(Response Time)  Sensitivity ^^2']*0.2

#calculating SLA* SP(Response Time)  Sensitivity ^^2

In [ ]:
tocode['SLA* SP(Response Time)  Sensitivity ^^2 / Average Response Time of SaaS_ID'] = tocode['SLA* SP(Response Time)  Sensitivity ^^2']/Average_Response_Time_of_SaaS_ID


#calculating SLA* SP(Response Time)  Sensitivity ^^2 / Average Response Time of SaaS_ID

In [ ]:
tocode['Percentage of Response time'] = (tocode['SLA* SP(Response Time)  Sensitivity ^^2 / Average Response Time of SaaS_ID']/0.2)*100


#calculating Percentage of Response time

In [ ]:
response_table = tocode[["SaaS_ID","Response Time(ms)","SP(Response Time)  Sensitivity ^^2","SLA* SP(Response Time)  Sensitivity ^^2","SLA* SP(Response Time)  Sensitivity ^^2 / Average Response Time of SaaS_ID","Percentage of Response time"]]

#Total response Table Calculated and printed 

response_table

   SaaS_ID  ...  Percentage of Response time
0      SP1  ...                    83.076923
1      SP2  ...                     9.230769
2      SP3  ...                    20.769231
3      SP4  ...                    20.769231
4      SP5  ...                    36.923077
5      SP6  ...                    83.076923
6      SP7  ...                   113.076923
7      SP8  ...                     9.230769
8      SP9  ...                   113.076923
9     SP10  ...                    20.769231
10    SP11  ...                   113.076923
11    SP12  ...                   113.076923
12    SP13  ...                    20.769231
13    SP14  ...                    57.692308
14    SP15  ...                    57.692308
15    SP16  ...                    20.769231
16    SP17  ...                    57.692308
17    SP18  ...                     9.230769
18    SP19  ...                    20.769231
19    SP20  ...                    57.692308
20    SP21  ...                    57.692308
21    SP22  ...                     9.230769
22    SP23  ...                    36.923077
23    SP24  ...                    57.692308

[24 rows x 6 columns]

In [ ]:
tocode['SP(Cost)  Sensitivity ^^2'] = tocode['Cost($)']**2
#calculating SP(Cost)  Sensitivity ^^2

In [ ]:
Average_Cost_of_SaaS_ID = tocode["Cost($)"].mean(axis=0)


#calculating Average_Cost_of_SaaS_ID

In [ ]:
tocode['SLA* SP(Cost)  Sensitivity ^^2'] = tocode['SP(Cost)  Sensitivity ^^2']*0.5

#calculating SLA* SP(Response Time)  Sensitivity ^^2

In [32]:
tocode['SLA* SP(Cost)  Sensitivity ^^2 / Average Cost of SaaS_ID'] = tocode['SLA* SP(Cost)  Sensitivity ^^2']/Average_Cost_of_SaaS_ID


#calculating SLA* SP(Response Time)  Sensitivity ^^2 / Average Response Time of SaaS_ID

In [33]:
Cost_table = tocode[["SaaS_ID","Cost($)","SP(Cost)  Sensitivity ^^2","SLA* SP(Cost)  Sensitivity ^^2","SLA* SP(Cost)  Sensitivity ^^2 / Average Cost of SaaS_ID"]]

#Total response Table Calculated and printed 

Cost_table

   SaaS_ID  ...  SLA* SP(Cost)  Sensitivity ^^2 / Average Cost of SaaS_ID
0      SP1  ...                                           0.111568
1      SP2  ...                                           0.624796
2      SP3  ...                                           0.030370
3      SP4  ...                                           0.695570
4      SP5  ...                                           0.068333
5      SP6  ...                                           0.212126
6      SP7  ...                                           0.474422
7      SP8  ...                                           0.275505
8      SP9  ...                                           0.408310
9     SP10  ...                                           0.252069
10    SP11  ...                                           0.223747
11    SP12  ...                                           0.019321
12    SP13  ...                                           0.096844
13    SP14  ...                                           0.058920
14    SP15  ...                                           0.264723
15    SP16  ...                                           0.221789
16    SP17  ...                                           0.437996
17    SP18  ...                                           0.245858
18    SP19  ...                                           0.488819
19    SP20  ...                                           0.184429
20    SP21  ...                                           0.165349
21    SP22  ...                                           0.318439
22    SP23  ...                                           0.179122
23    SP24  ...                                           0.277687

[24 rows x 5 columns]