<a href="https://colab.research.google.com/github/lokesh31333/Python/blob/master/Z.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
from matplotlib import pyplot as plt

In [4]:
excel_file = 'z.xlsx'
tocode = pd.read_excel(excel_file)
# opening Excel File

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
tocode

   SaaS_ID  ...  Service Completion Time for Service - B
0      SP1  ...                                 1.947587
1      SP2  ...                                 1.974140
2      SP3  ...                                 1.644647
3      SP4  ...                                 2.069013
4      SP5  ...                                 1.767420
5      SP6  ...                                 2.028807
6      SP7  ...                                 2.242067
7      SP8  ...                                 1.803287
8      SP9  ...                                 2.210567
9     SP10  ...                                 1.855427
10    SP11  ...                                 2.103440
11    SP12  ...                                 1.889047
12    SP13  ...                                 1.732653
13    SP14  ...                                 1.822047
14    SP15  ...                                 1.996613
15    SP16  ...                                 1.835473
16    SP17  ...                                 2.091460
17    SP18  ...                                 1.785073
18    SP19  ...                                 1.982127
19    SP20  ...                                 1.942100
20    SP21  ...                                 1.927627
21    SP22  ...                                 1.828907
22    SP23  ...                                 1.871480
23    SP24  ...                                 2.005273

[24 rows x 5 columns]

In [8]:
tocode["Total Service Accesible Time"] = (tocode["Service Accessible time for Service A"] + tocode["Service Accessible time for Service B"] )


# Calculating the Total Service Accesible Time

In [9]:
tocode["Total Service Completion time"] = (tocode["Service Completion Time for Service - A"] + tocode["Service Completion Time for Service - B"])

In [10]:
tocode["AVG No. of Services by the provider"] = tocode["Total Service Completion time"]/tocode["Total Service Accesible Time"]

In [11]:
tocode["Utilization(%) of services to customer"] = (1/tocode["AVG No. of Services by the provider"])*100

In [14]:
Final_Table = tocode[["SaaS_ID","Service Accessible time for Service A","Service Accessible time for Service B","Total Service Accesible Time","Service Completion Time for Service - A","Service Completion Time for Service - B","Total Service Completion time","AVG No. of Services by the provider","Utilization(%) of services to customer"]]
Final_Table

   SaaS_ID  ...  Utilization(%) of services to customer
0      SP1  ...                               20.538239
1      SP2  ...                                6.753996
2      SP3  ...                               12.160667
3      SP4  ...                                9.666443
4      SP5  ...                               15.087906
5      SP6  ...                               19.716024
6      SP7  ...                               20.814130
7      SP8  ...                                7.393907
8      SP9  ...                               21.110726
9     SP10  ...                               10.779192
10    SP11  ...                               22.185880
11    SP12  ...                               24.703819
12    SP13  ...                               11.542990
13    SP14  ...                               18.294445
14    SP15  ...                               16.694937
15    SP16  ...                               10.896372
16    SP17  ...                               15.937830
17    SP18  ...                                7.469348
18    SP19  ...                               10.090173
19    SP20  ...                               17.163551
20    SP21  ...                               17.292422
21    SP22  ...                                7.290330
22    SP23  ...                               14.248972
23    SP24  ...                               26.596540

[24 rows x 9 columns]